name: StarkLotto CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "**"
      - ".github/workflows/**"

  push:
    branches:
      - dev
    paths:
      - "packages/snfoundry/contracts/**"
      - ".github/workflows/**"

jobs:
  # -------------------------
  # 1. StarkLotto General CI
  # -------------------------
  build-and-test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Scarb
      uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: "2.7.0"

    - name: Setup snfoundry
      uses: foundry-rs/setup-snfoundry@v3
      with:
        tool-versions: ./.tool-versions

    - name: Skip global scarb fetch due to version conflicts
      run: echo "Skipping scarb fetch and build in main project because of dependency conflicts"

    - name: Run integration tests for contracts package
      run: snforge test -- -v --print-logs
      working-directory: ./packages/snfoundry/contracts
      env:
        RUST_BACKTRACE: 1
        SNFORGE_FORMAT: pretty

  # -------------------------
  # 2. Snfoundry Contracts CI
  # -------------------------
  build-and-test-contracts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      - name: Setup snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./.tool-versions

      - name: Compile contracts
        run: scarb build
        working-directory: ./packages/snfoundry/contracts

      - name: List tests
        run: snforge test -- --list
        working-directory: ./packages/snfoundry/contracts

      - name: Run snfoundry tests (verbose + logs)
        run: snforge test -- -v --print-logs
        working-directory: ./packages/snfoundry/contracts
        env:
          RUST_BACKTRACE: 1
          SNFORGE_FORMAT: pretty
